server:
  port: 8080

spring:

  profiles:
    active: local # local profile 사용하기 위한 설정

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:23306
    username: root
    password: 1234
    driver-class-name: com.

  flyway:
    enabled: true #false # true # 기본값 = true 이지만, flyway를 사용하고 있음을 명시해줍니다.
    #enabled: false
    #baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate


flyway:
  enabled: false # 운영환경에서 flyway가 동작하는 것을 방지하기 위하여 false로 설정
